# Generated by Django 4.0.8 on 2022-12-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_mapdetailpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('fill', 'Fill'), ('circle', 'Circle')], max_length=255)),
                ('source_layer', models.CharField(blank=True, max_length=255, null=True)),
                ('source_type', models.CharField(choices=[('geojson', 'GeoJSON'), ('vector', 'Vector')], max_length=255)),
                ('url', models.URLField()),
            ],
        ),
    ]
