# Generated by Django 4.0.8 on 2022-12-30 15:47

import districtrcms.client.models
from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdetailpage',
            name='sources',
            field=wagtail.fields.StreamField([('sources', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('source', wagtail.snippets.blocks.SnippetChooserBlock(districtrcms.client.models.Source)), ('layers', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock()), ('type', wagtail.blocks.ChoiceBlock(choices=[('fill', 'Fill'), ('line', 'Line'), ('symbol', 'Symbol'), ('circle', 'Circle')])), ('layout', wagtail.blocks.RawHTMLBlock()), ('paint', wagtail.blocks.RawHTMLBlock()), ('filter', wagtail.blocks.RawHTMLBlock()), ('is_interactive', wagtail.blocks.BooleanBlock())])))])))], blank=True, use_json_field=True),
        ),
    ]
