# Generated by Django 4.0.8 on 2023-01-24 13:13

import districtrcms.client.models
import django.contrib.gis.db.models.fields
from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_mapdetailpage_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdetailpage',
            name='bounds_ne',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='mapdetailpage',
            name='bounds_sw',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='mapdetailpage',
            name='sources',
            field=wagtail.fields.StreamField([('sources', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('source', districtrcms.client.models.APISourceChooserBlock(districtrcms.client.models.Source)), ('layers', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock()), ('id', wagtail.blocks.CharBlock()), ('type', wagtail.blocks.ChoiceBlock(choices=[('fill', 'Fill'), ('line', 'Line'), ('symbol', 'Symbol'), ('circle', 'Circle')])), ('layout', wagtail.blocks.RawHTMLBlock()), ('paint', wagtail.blocks.RawHTMLBlock()), ('filter', wagtail.blocks.RawHTMLBlock()), ('is_interactive', wagtail.blocks.BooleanBlock(blank=True))])))])))], blank=True, use_json_field=True),
        ),
    ]
